let strip = neopixel.create(DigitalPin.P0, 144, NeoPixelMode.RGB)
let anim = pixelanimation.initAnimationStrip(strip)
let eff = new pixelanimation.FeuerRoundAnimation(1000)
anim.play(eff)
/*
anim.play(eff)
eff = new pixelanimation.RotateAnimation(1000)
anim.queue(eff)
eff = new pixelanimation.RotateAnimation(1000, true)
anim.queue(eff)
eff = new pixelanimation.SetRainbowAnimation(2000)
anim.queue(eff)
*/
input.onButtonPressed(Button.A, function () {
    let eff = new pixelanimation.SetRainbowAnimation(2000)
    anim.play(eff)
    eff = new pixelanimation.RotateAnimation(500)
    anim.queue(eff)
    anim.queue(eff)
    anim.queue(eff)
    anim.queue(eff)
    eff = new pixelanimation.RotateAnimation(500, true)
    anim.queue(eff)
    anim.queue(eff)
    anim.queue(eff)
    anim.queue(eff)
})