let strip = neopixel.create(DigitalPin.P0, 10, NeoPixelMode.RGB)
let anim = pixelanimation.initAnimationStrip(strip)
let eff = new pixelanimation.SetRainbowAnimation(1000)
anim.play(eff)
eff = new pixelanimation.RotateAnimation(1000)
anim.queue(eff)
eff = new pixelanimation.RotateAnimation(1000, true)
anim.queue(eff)
pause(1500)
eff = new pixelanimation.SetRainbowAnimation(2000)
anim.play(eff)
pause(500)
anim.stopAnimation()